import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Item from "@/components/item";
import LeftSidebar from "@/components/sidebar-left";
import RightSidebar from "@/components/sidebar-right";
import Announcement from "@/components/announcement";
import Assignment from "@/components/assignment";
import Material from "@/components/material";

export const getServerSideProps = async () => {
  // const baseUrl = process.env.NODE_ENV === 'PRODUCTION' ? 'https://test.com' : 'http://localhost:3000'
  const baseUrl = 'https://ubiquitous-broccoli-j79q6grrx67hqrpp-3000.app.github.dev'
  const classListRest = await fetch(`${baseUrl}/api/classList`)
  const { classes, err: classErr } = await classListRest.json()
  console.log(classErr);

  const res = await fetch(`${baseUrl}/api/classPosts?classes=${classes.map(gClass => gClass.id).join(",")}`);
  const { posts, err: postErr } = await res.json();
  console.log(postErr);
  posts.sort((a,b) => {
      let first = new Date(a.dueDate || a.creationTime);
      let second = new Date(b.dueDate || b.creationTime);
      return first > second ? 1 : -1
  })
  return { props: { posts }}
}
export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LeftSidebar />
      <RightSidebar />
      <main
        style={{
          // background: "red",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          marginTop: "100px",
          flexDirection: "column",
        }}
      >
        {
          posts.map(post => {
            switch (post.type) {
              case "classwork":
                return <Assignment key={post.id} data={post} />
              case "material":
                return <Material key={post.id} data={post} />
              case "announcement":
                return <Announcement key={post.id} data={post} />
              default:
                return <></>
            }
          })
        }
      </main>
    </>
  );
}
